from concurrent.futures import Future
from datetime import timedelta
from os import PathLike
from typing import (
    Any,
    Callable,
    Coroutine,
    Generic,
    Literal,
    ParamSpec,
    Protocol,
    TypeVar,
    overload,
)

P = ParamSpec("P")
T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)

class _Cached(Protocol[T_co]):
    # update_cache is a reserved wrapper keyword, not part of the original P.
    def __call__(self, *args: Any, update_cache: bool = ..., **kwargs: Any) -> T_co: ...
    def cache_key(self, *args: Any, **kwargs: Any) -> str: ...
    def invalidate(self, *args: Any, **kwargs: Any) -> int | Coroutine[Any, Any, int]: ...

class _AsyncCached(_Cached[Coroutine[Any, Any, T_co]], Protocol[T_co]):
    async def __call__(self, *args: Any, update_cache: bool = ..., **kwargs: Any) -> T_co: ...
    def cache_key(self, *args: Any, **kwargs: Any) -> str: ...
    async def invalidate(self, *args: Any, **kwargs: Any) -> int: ...

class _CacheDecorator(Protocol):
    @overload
    def __call__(self, function: Callable[..., Coroutine[Any, Any, T]]) -> _AsyncCached[T]: ...
    @overload
    def __call__(self, function: Callable[..., T]) -> _Cached[T]: ...

class _Destination(Protocol):
    def write(self, data: Any, /) -> Any: ...
    def close(self) -> None: ...

class Persistence(Generic[P, T]):
    def __init__(
        self, fs: str | PathLike[str] | _Destination | Callable[[], _Destination],
        function: Callable[P, T], *, write_mode: Literal["bytes", "file"] = ...,
    ) -> None: ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T: ...
    @overload
    def submit(
        self: Persistence[P, Coroutine[Any, Any, T_co]], *args: P.args, **kwargs: P.kwargs,
    ) -> Coroutine[Any, Any, Future[T_co]]: ...
    @overload
    def submit(self, *args: P.args, **kwargs: P.kwargs) -> Future[T]: ...
    def flush(self) -> None: ...
    async def aflush(self) -> None: ...
    def close(self) -> None: ...
    async def aclose(self) -> None: ...
    def __enter__(self) -> Persistence[P, T]: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def __aenter__(self) -> Persistence[P, T]: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

def mem_cache(cache_dir: str | PathLike[str] | None = ...) -> Callable: ...
def clear_mem(path: str | PathLike[str] = ..., cache_dir: str | PathLike[str] | None = ...) -> None: ...
def redis_cache(
    expires: int | float | timedelta | None = ...,
    prefix: str | None = ...,
    redis_connector: Callable[[], Any] | None = ...,
    result_assert: Callable[[Any], bool] | None = ...,
    *, namespace: str | None = ..., version: str = ...,
    key_fn: Callable[..., Any] | None = ...,
    codec: Literal["pickle", "json"] = ..., cache_none: bool = ...,
) -> _CacheDecorator: ...
def persistence(
    fs: str | PathLike[str] | _Destination | Callable[[], _Destination],
    f: Callable[P, T], *, write_mode: Literal["bytes", "file"] = ...,
) -> Persistence[P, T]: ...
