name: MongoDB Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/jcutil/drivers/mongo.py'
      - 'tests/test_mongo.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/jcutil/drivers/mongo.py'
      - 'tests/test_mongo.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        mongodb-version: ['4.4', '5.0', '6.0']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 27017
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -e .
    
    - name: Test with pytest
      run: |
        pytest tests/test_mongo.py -v 